- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Deploy DHCP config
  template:
    src: dhcp.conf.j2
    dest: /etc/dnsmasq.d/dhcp.conf
  notify: Restart dnsmasq
